# Generated by Django 5.0.2 on 2024-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('is_enable', models.BooleanField(default=False)),
                ('banner_send_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('promotion_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'apps',
            },
        ),
        migrations.CreateModel(
            name='FullVoterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sr_no', models.IntegerField(null=True)),
                ('ac_no', models.IntegerField()),
                ('booth_no', models.IntegerField()),
                ('epic_no', models.CharField(max_length=100)),
                ('voter_sr_no', models.IntegerField(blank=True)),
                ('booth_address_hindi', models.TextField(blank=True, null=True)),
                ('house_no', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('full_name_english', models.CharField(blank=True, max_length=255)),
                ('full_name_hindi', models.CharField(blank=True, max_length=255)),
                ('first_name_english', models.CharField(blank=True, max_length=100)),
                ('first_name_hindi', models.CharField(blank=True, max_length=100)),
                ('middle_name_english', models.CharField(blank=True, max_length=100)),
                ('middle_name_hindi', models.CharField(blank=True, max_length=100)),
                ('last_name_english', models.CharField(blank=True, max_length=100)),
                ('last_name_hindi', models.CharField(blank=True, max_length=100)),
                ('gender_english', models.CharField(blank=True, max_length=10)),
                ('gender_hindi', models.CharField(blank=True, max_length=10)),
                ('address_english', models.TextField(blank=True, null=True)),
                ('address_hindi', models.TextField(blank=True, null=True)),
                ('booth_address_english', models.TextField(blank=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('is_voted', models.BooleanField(default=False)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('is_activist', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('updated_address', models.TextField(blank=True)),
                ('post', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Voter',
            },
        ),
    ]
