# Generated by Django 5.0.2 on 2024-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullvoterdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='fullvoterdetail',
            name='sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
