# Generated by Django 5.0.2 on 2024-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_remove_fullvoterdetail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
